[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
directory = "netlify/functions"

[[edge_functions]]
path = "/*"
function = "next"

[build.cache]
paths = [
  ".next/cache",
  "node_modules/.cache"
]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 