[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18.17.0"
NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/next"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/functions/next"
status = 200
force = true

[functions]
node_bundler = "esbuild"
external_node_modules = ["@auth/mongodb-adapter", "mongodb", "mongoose"]
included_files = ["node_modules/mongodb/**/*"]

[functions.timeout]
external_node_modules = ["@auth/mongodb-adapter", "mongodb", "mongoose"]

[build.cache]
paths = [
  ".next/cache",
  "node_modules/.cache"
] 